name: poi_maps
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  iconsax: ^0.0.8
  get: ^4.6.6
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  get_storage: ^2.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  connectivity_plus: ^6.0.2
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  http: ^1.2.1
  app_settings: ^5.1.1
  modal_bottom_sheet: ^3.0.0
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  webview_flutter: ^4.7.0
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1









  #----- Maps Packages -----#
  google_maps_flutter: ^2.6.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  uuid: ^4.4.0
  flutter_polyline_points: ^2.0.0
  dio: ^5.4.3+1
  location: ^6.0.1

  #---- Firebase Packages ----#
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1


  #------Launcher Icon-----#
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/images/home_icons/

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

  
  
