// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7mtvMv5moc2YF7atfsvaV4GXMt4zmEH0',
    appId: '1:969117289567:web:96dd9c0127cd93462d5fea',
    messagingSenderId: '969117289567',
    projectId: 'finder-419720',
    authDomain: 'finder-419720.firebaseapp.com',
    storageBucket: 'finder-419720.appspot.com',
    measurementId: 'G-H0CZPPH3S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIZbWWPl2MZOiPDS1Sw7NO7j2rmWDr7Kc',
    appId: '1:969117289567:android:5ecc12b472619e5f2d5fea',
    messagingSenderId: '969117289567',
    projectId: 'finder-419720',
    storageBucket: 'finder-419720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8fOBoHRNT3BNw192EWN8oHDulbp3e_k',
    appId: '1:969117289567:ios:d501c7fdc3bf5d7c2d5fea',
    messagingSenderId: '969117289567',
    projectId: 'finder-419720',
    storageBucket: 'finder-419720.appspot.com',
    iosBundleId: 'com.example.poiMaps',
  );
}
